Fe profile details page
hatchways/team-teak pull request #101
Opened 2022-02-07 16:32 UTC by wiroger9595

### What this PR does (required):
- create front end profile detail page make a page responsive
- user can send a request form to book 

### Screenshots / Videos (front-end only):
- desktop 
![Screen Shot 2022-02-07 at 11 57 10 PM](https://user-images.githubusercontent.com/23616272/152824208-7ec01b6d-8985-48ea-a816-d2e4262df5c0.png)

- mobile
![Screen Shot 2022-02-07 at 11 57 36 PM](https://user-images.githubusercontent.com/23616272/152824259-a9139e45-02ad-4866-8da1-0ef5922fa205.png)

### Any information needed to test this feature (required):
- request form time booking have yup that end time can't be shorter than start time and start time will base on local time on the computer
- yup will validate any base on date and 

### Any issues with the current functionality (optional):
-The navbar page has not responsive on mobile and navbar components. 
- have not add if pet sitter's time been book
- there have lots file changed, my change is in src/pages/ProfileDetails

2022-02-09 14:06 UTC, ugur-akin reviewed
Hello fellow contributor! I'm a robot and I'll be reviewing your PR for its Communication aspects *\*beep boop\**!

### Let's start with the pull request title:

Your title looks good overall, thanks for nicely formatting it! &#9989;


### Then there is the pull request summary:

Your summary looks good overall, thanks for paying attention to your communication! &#9989;



All in all, well-communicating pull requests is an important skill, hence we encourage all candidates to build strong habits in this regard. For additional information, [this article](https://hugooodias.medium.com/the-anatomy-of-a-perfect-pull-request-567382bb6067) touches on some more important points.
  
Good luck &#127881;

2022-02-09 14:08 UTC, ugur-akin commented
Hi @wiroger9595 , sorry about the comment above 😅 It's part of a new feature we're working and I just needed a PR to test it on 👍🏼 

Cheers,

2022-02-11 15:04 UTC, jtingling commented on client/src/components/AvatarDisplay/AvatarDisplay.tsx
> +      </Avatar>
From a design perspective, would a generic avatar image be better like the pet sitter paw print?

2022-02-11 15:38 UTC, jtingling commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +  });
It looks like this code is used for resizing page components based on hardcoded breakpoints. Consider using standardized breakpoints provided with mui.

2022-02-11 15:42 UTC, jtingling commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +          mb={windowWidth < 1200 ? 3 : 0}
See comment above.

2022-02-11 15:50 UTC, jtingling commented on client/src/pages/ProfileDetails/useStyles.tsx
> +    },
Mui provides `theme.breakpoints` for this.

2022-02-24 18:24 UTC, moffatethan commented
@wiroger9595 Any ETA on these changes Rob?

2022-03-03 02:14 UTC, moffatethan requested changes
Why are we deleting the settings page?

2022-03-04 01:06 UTC, moffatethan requested changes
Lots of merge conflicts from the approved PRs, please be careful when addressing them!

2022-03-04 14:45 UTC, closed without merging