created payment controllers
hatchways/team-teak pull request #102
Opened 2022-02-08 13:12 UTC by MUGABA

### What this PR does (required):
-add the payment through `post /payments`
- retrieves all payments for the logged in user through `get /payments`
- get a single payment details through `get /payments/:paymentId`
- cancel the payment through `put /payments/: paymentId/cancel` 
- make a payment through `post /payments/:paymentId/pay`

2022-02-08 14:48 UTC, ezeilo-su reviewed
Looks good overall!
Happy coding!

2022-02-08 14:48 UTC, ezeilo-su commented on server/controllers/payment.js
> +// @access Public
Good documentation :+1:

2022-02-08 14:48 UTC, ezeilo-su commented on server/controllers/payment.js
> +  const { sitterId, rate, startTime, endTime } = req.body;
Good security practice

2022-02-08 14:48 UTC, ezeilo-su commented on server/controllers/payment.js
> +// @access Private
:+1:

2022-02-08 14:48 UTC, ezeilo-su commented on server/controllers/payment.js
> +    res.status(400);
I'd suggest a `500` status for this since it's not a client error.

2022-02-17 19:00 UTC, moffatethan requested changes

2022-02-17 19:00 UTC, moffatethan commented on server/controllers/payment.js
> +      payment: payment,
We can just pass 

```
{
   success: {
      payment 
   }
}
```

2022-02-17 19:00 UTC, moffatethan commented on server/controllers/payment.js
> +      payment: payment,
Ditto throughout the PR

2022-02-17 19:00 UTC, moffatethan commented on server/controllers/payment.js
> +      source: "Hatchways",
Let's not have the source be Hatchways - remember the app is called Loving Sitter 🙂

2022-02-22 17:45 UTC, moffatethan commented
@MUGABA Any ETA on these changes? 🙂

2022-02-24 18:24 UTC, moffatethan commented
@MUGABA Checking in again - any ETA?

2022-02-27 08:54 UTC, closed without merging