Customer Profile Image feature with Cloundinary integration
hatchways/team-teak pull request #115
Opened 2022-02-16 22:52 UTC by jtingling

### What this PR does (required):
Customers can update and delete profile photos to their profile. Images are stored with Cloudinary. A static url is extracted from the response which is then added to the `photo` field on the `profile` model. State is updated by calling `updateLoginContext` instead of using local component state which triggers a re-render to display the image. This approach should allow #38 and other messaging related issues to use the `profile.photo` as well.

### Screenshots / Videos (front-end only):
#### Avatar
![Avatar](https://user-images.githubusercontent.com/20543097/154370556-06af8ba0-ce22-4f4b-9206-4927255cf4b1.jpg)
### Default Avatar
![NoAvatar](https://user-images.githubusercontent.com/20543097/154370566-7a285220-08aa-49c0-beae-d5ac5ea11614.jpg)

### Any information needed to test this feature (required):
- Log in and upload an image from your device.
- Click the `delete photo` button to remove photo

### Any issues with the current functionality (optional):
- `Multer` stores images to disk. There may be issues with scalability as the image files are not removed. Possible solutions may be to run `unlink` or `fs.rmdir` on the image directory to avoid this. I had trouble getting this to work consistently.

2022-02-17 20:53 UTC, ezeilo-su reviewed
Good progress so far with this one.

2022-02-17 20:53 UTC, ezeilo-su commented on client/src/components/Navbar/Navbar.tsx
> +                  {console.log(profile?.photo)}
We don't need this console log here. Please remove it.

2022-02-24 19:13 UTC, moffatethan requested changes

2022-02-24 19:13 UTC, moffatethan commented on server/utils/cloudinary.js
> +    api_secret: process.env.CLOUDINARY_API_SECRET,
Let's update the sample.env with these new environment variables please. Just the key names not the values

2022-03-03 02:18 UTC, moffatethan approved these changes

2022-03-03 20:38 UTC, merged