finished demo user setup on the ui
hatchways/team-teak pull request #50
Opened 2022-01-13 21:55 UTC by MUGABA

### What this PR does (required):
- list PR functionality here

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2022-01-13 21:56 UTC, MUGABA commented
![Screenshot 2022-01-14 005600](https://user-images.githubusercontent.com/42658956/149415277-79099457-d237-4fe4-b216-3736963c9518.png)

2022-01-14 05:39 UTC, MUGABA commented
![Screenshot 2022-01-14 083748](https://user-images.githubusercontent.com/42658956/149457474-a5a0db0c-ecd7-4bb3-a8cd-bf3f853a756a.png)

2022-01-14 21:17 UTC, ezeilo-su reviewed
Good work with this one :+1:

2022-01-14 21:17 UTC, ezeilo-su commented on server/controllers/auth.js
> +    console.log("I reached here");
You can remove the code used for debugging to keep your code clean.

2022-01-15 03:04 UTC, moffatethan requested changes
Just some quick chnages, looks like something in your editor is sorting imports. This might cause a lot of files changed so maybe let's turn that off for this project. 

Also, please fill out the PR templates. This is a collaborative project, letting reviewers know change logs in the PR and any notes and pictures of UI (**for front-end work only**) will help the process a lot more. Leaving it completely blank isn't a good sign and seems rushed.

In future PRs, if I don't see these templates filled out I will pause reviews on it until it is filled out 👍🏻

2022-01-15 03:04 UTC, moffatethan commented on server/controllers/auth.js
> +    password,
Should be no back-end changes in this ticket since it's front-end. Please revert this file with git. Thanks!

2022-01-15 03:04 UTC, moffatethan commented on client/src/helpers/APICalls/login.ts
> +  console.log('Its working');
Please remove the debugging logs from your PRs before making them.

2022-01-18 16:07 UTC, merged