created ui for manage bookings ui issue  and made it responsive
hatchways/team-teak pull request #64
Opened 2022-01-17 17:15 UTC by MUGABA

### What this PR does (required):
- list PR functionality here

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a scr
![Screenshot 2022-01-17 200354](https://user-images.githubusercontent.com/42658956/149812793-f5b59109-40ff-4510-b39b-ce931a36c5df.png)
eenshot/video of the problem, along with detailed console outputs where applicable

![Screenshot 2022-01-17 200449](https://user-images.githubusercontent.com/42658956/149812892-037a0c99-86a0-4b58-9ac4-dc60abfa8378.png)

![Screenshot 2022-01-17 200728](https://user-images.githubusercontent.com/42658956/149812918-2f7cb8dd-cf2f-44bf-89d0-7ce9960b26ab.png)

![Screenshot 2022-01-17 200831](https://user-images.githubusercontent.com/42658956/149812945-692f447e-68c0-4e01-a8a6-9da30d766edb.png)

2022-01-17 19:38 UTC, ezeilo-su commented
Hey @MUGABA, please fill out the PR templates and link your ticket in the PR before we can proceed with code review.

2022-01-17 19:50 UTC, MUGABA commented
> Hey @MUGABA, please fill out the PR templates and link your ticket in the PR before we can proceed with code review.

Hello! unless when there a problem when I was filling the form, though I have filled in and submitted again! For linking the issue I did it prior to creating the pr

2022-01-18 16:31 UTC, moffatethan requested changes
Pausing review on this

@MUGABA PR template is not filled out properly. Screenshots are provided but everything else is still the template information.

2022-01-21 01:09 UTC, moffatethan requested changes
Not sure on the UI overall, it's not the greatest. Everything appears squished and far apart. Could we work on this a bit more @MUGABA. 

Thanks!

2022-01-21 01:09 UTC, moffatethan commented on client/src/App.tsx
> +                <Route path="/booking" component={BookingsPage} />
`/my-jobs` is the page we want so it works in the navbar.

2022-01-21 01:09 UTC, moffatethan commented on client/src/components/ManageBookings/BookingCalendar/BookingCalendar.tsx
> +    return 'yes';
Generally we should pass back true/false for truthy or falsey statements.

2022-01-21 01:09 UTC, moffatethan commented on client/src/components/ManageBookings/CurrentBooking/CurrentBookingCard.tsx
> +        YOUR NEXT BOOKING
Generally against using uppercase like this. Rather, we should set the CSS to transform the text to uppercase. Screen readers will read this out letter by letter which would be very annoying for a user with disabilities.

2022-01-21 01:09 UTC, moffatethan commented on client/src/components/ManageBookings/CurrentBooking/useStyles.ts
> +    // borderStyle: 'solid',
Remove please

2022-01-21 01:09 UTC, moffatethan commented on client/src/components/ManageBookings/CurrentBooking/useStyles.ts
> +    // justifyContent: 'space-between',
Remove please

2022-01-21 01:18 UTC, moffatethan commented
Also - I don't like the calendar font. Could you try making it match our font? Or https://www.youtube.com/watch?v=5jRrVqRWqsM here is a video on creating a calendar in React if you want to take another stab at it, just make sure to design the UI to be like the mocks.

2022-01-25 16:43 UTC, moffatethan requested changes
Lots of changes in this PR, I think we need to base the branch properly.

2022-02-01 18:08 UTC, moffatethan requested changes
Please address merge conflicts

2022-02-02 20:13 UTC, moffatethan approved these changes

2022-02-02 20:25 UTC, merged