Account type added on registration controller
hatchways/team-teak pull request #68
Opened 2022-01-18 22:46 UTC by chinexman

### What this PR does (required):
Account type added on registration controller to alter their account type if  the  user is a petSitter when creating a new profile 
### Screenshots / Videos (front-end only):

### Any information needed to test this feature (required):
 during sign up as a new user, click on the become a sitter button  from the navbar menuitems

### Any issues with the current functionality (optional):
-

2022-01-19 01:44 UTC, wiroger9595 commented
you need to fix the conflicts before ethan check the review

2022-01-19 05:13 UTC, MUGABA commented on server/controllers/auth.js
> +
This is good work, ternary operators, Though I still think there is more attributes, on the profile mode

2022-01-19 05:16 UTC, MUGABA requested changes
I think there is a profile controller where in my opinion you might need to update the profile from! Please check with @moffatethan  and see whether what am saying is okay, do not take my comment for it

2022-01-19 05:17 UTC, MUGABA commented
And once again link your issue and fill the pr template

2022-01-21 01:36 UTC, moffatethan commented
Need to close this PR - we're going to be taking a different approach which makes this work unnecessary. 👍🏻

2022-01-21 01:36 UTC, closed without merging