make availability ui page
hatchways/team-teak pull request #74
Opened 2022-01-21 15:45 UTC by wiroger9595

### What this PR does (required):
- make availability UI page

### Screenshots / Videos (front-end only):

<img width="1613" alt="Screen Shot 2022-01-21 at 11 43 07 PM" src="https://user-images.githubusercontent.com/23616272/150556177-845b88aa-1a5e-4fa1-9f43-ff731af5873c.png">

### Any information needed to test this feature (required):
- just basic UI style made, need more work and recommendation of editing the page

### Any issues with the current functionality (optional):
- need to add backend model and controller after to make this page work

2022-01-25 23:40 UTC, moffatethan requested changes
Please update the component to not use v4. Let's get rid of that package in the project, I don't want to use v4. Some other comments to address.

2022-01-25 23:40 UTC, moffatethan commented on client/src/pages/Settings/Availability/Availability.tsx
> +  // date?(date: Date): string | null;
This can be removed

2022-01-25 23:40 UTC, moffatethan commented on client/src/pages/Settings/Availability/Availability.tsx
> +import 'date-fns';
Importing just `date-fns` isn't really doing anything for us 

import dateFns from 'date-fns'`

Also, this should be moved to the top of the file for organization.

2022-01-25 23:40 UTC, moffatethan commented on client/src/pages/Settings/Availability/Availability.tsx
> +import { Button, Input, InputAdornment, IconButton, Dialog, DialogActions } from '@material-ui/core';
This is v4 of Material UI. We use v5 here, please update this.

2022-01-25 23:40 UTC, moffatethan commented on client/src/pages/Settings/Availability/Availability.tsx
> +import ListItemIcon from '@mui/material/ListItemIcon';
import { . . . } from '@mui/core'

2022-01-25 23:41 UTC, moffatethan commented
Also - please add in buttons to create multiple schedules.

2022-01-27 15:49 UTC, closed without merging

2022-01-27 15:50 UTC, wiroger9595 commented
There have some issue, I will push new ticket