Profile users list
hatchways/team-teak pull request #81
Opened 2022-01-25 19:24 UTC by chinexman

### What this PR does (required):
Displays the lists of user profile. it has a search field , with which, a user profile can be search. it display the location of pit sitters , the amount the charge per hour for bulking.

### Screenshots / Videos (front-end only):
![Screenshot 2022-01-25 at 20 10 56](https://user-images.githubusercontent.com/25329964/151044937-94f4e329-63c3-412d-8978-00683c259762.png)
![Screenshot 2022-01-25 at 20 10 36
![Screenshot 2022-01-25 at 20 10 17](https://user-images.githubusercontent.com/25329964/151045103-18509817-6da2-4066-9f4d-bf13f12812ef.png)
](https://user-images.githubusercontent.com/25329964/151044987-1e949341-1fc2-41f9-9c4f-9874833dca1f.png)

### Any information needed to test this feature (required):
run the app on the client  with "yarn start", ensure your server is running as well by runing  "yarn dev". on the url, type the link  "localhost:3000/profile/listing" to display the list of profiles

2022-01-26 00:27 UTC, moffatethan requested changes
Hey Chinedu, thanks for working on this. But I noticed something very concerning. **We're using v4 of MUI**. We need to use v5 of MUI. I am not going to approve this at all until that is removed and all the files changed are converted to v5 variants. 

Thank you!

2022-01-26 00:27 UTC, moffatethan commented on client/src/App.tsx
> +                <Route path="/profile/listing" component={ProfileListing} />
The dashboard will be where we list the profiles, would make more sense to do the changes in that component rather than a new route.

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/Content.tsx
> +const Content: FC = () => {
`ProfileList` would be a better name for this component.

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/Header.tsx
> +      {/* <Stack spacing={4}> */}
Please remove this

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/Header.tsx
> +          />
We'd want to use Formik for doing our search.

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/Header.tsx
> +            // style={{ marginBottom: '30px' }}
Remove please

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/ProfileList.jsx
> +            <IconButton aria-label="settings">{/* <Rating name="size-medium" defaultValue={2} /> */}</IconButton>
Remove this please

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/ProfileList.jsx
> +import Typography from '@material-ui/core/Typography';
Again - we're using v4 of MUI here. We need to use v5 of MUI. Can we just get rid of that package so we aren't running into that issue?

2022-01-26 00:27 UTC, moffatethan commented on client/src/pages/ProfileListing/ProfileListing.tsx
> +        {/* <h1>profile header</h1> */}
Remove please

2022-02-08 20:36 UTC, jtingling commented
### What this PR does (required):
Displays sitter profile data. Search by location (ex. `Montreal, Quebec`) and date of week (ex. `Monday`) to search for users in the db automatically.

### Screenshots / Videos (front-end only):
![profileListing-demo](https://user-images.githubusercontent.com/20543097/153070716-f07f9ffe-5058-49bf-a7c8-62f01d71dcbd.gif)
![profileListing-responsive](https://user-images.githubusercontent.com/20543097/153070770-9dc0d440-bfda-45cb-86ee-0d2bc3e68b4e.gif)

### Any information needed to test this feature (required):
run the app on the client  with "yarn start", ensure your server is running as well by running  "yarn dev". on the url, type the link  "localhost:3000/dashboard" to display the list of profiles
]
### Issues
- Date input only works if using the DatePicker. Input via keyboard does not work.
- Ratings are hardcoded.

2022-02-09 05:34 UTC, MUGABA commented
This Pr has some change requests but the owner is off the team that's why am closing it. Plus it's being worked on by @jtingling

2022-02-09 05:34 UTC, closed without merging