Fe in notifications
hatchways/team-teak pull request #84
Opened 2022-01-28 05:51 UTC by wiroger9595

### What this PR does (required):
- do notification integrate with backend

### Screenshots / Videos (front-end
<img width="810" alt="Screen Shot 2022-01-28 at 1 23 32 PM" src="https://user-images.githubusercontent.com/23616272/151492293-4b65a3ea-b9b5-495f-bab1-d946d805ad09.png">
 only):

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- need to integrate with backend so it can show the result

2022-01-28 12:41 UTC, MUGABA commented on client/src/components/Navbar/Notification/Notification.tsx
> +          </React.Fragment>
There is away to group jsx elements with just an open and close tag `<></>`

2022-01-28 12:43 UTC, MUGABA commented on client/src/helpers/APICalls/notifications.ts
> +  return await fetch(`notication/all`, fetchOptions)
This can be just `notifications`

2022-02-06 17:12 UTC, MUGABA reviewed
Hey can you put all the api calls for the notifications in a single file.

2022-02-09 20:19 UTC, moffatethan requested changes

2022-02-09 20:19 UTC, moffatethan commented on client/src/helpers/APICalls/getNotifications.ts
> +export async function fetctAllNotications(): Promise<Notifications> {
`fetchAllNotifications` please be mindful of spelling

2022-02-09 20:19 UTC, moffatethan commented on client/src/helpers/APICalls/getNotifications.ts
> +export async function fetctAllUnreadNotications() {
`fetchAllUnreadNotifications`

2022-02-09 20:19 UTC, moffatethan commented on server/controllers/notification.js
> +  console.log(notificationByUserId);
Remove this console log 🙂

2022-02-09 20:19 UTC, moffatethan commented on server/controllers/notification.js
> +  console.log(userId);
Let's remove this console log as well

2022-02-09 20:19 UTC, moffatethan commented on server/controllers/notification.js
> +    // }
Let's remove this commented code 🙂

2022-02-09 20:19 UTC, moffatethan commented on server/controllers/notification.js
> +  // console.log(id);
Same here please 🙂

2022-02-09 20:19 UTC, moffatethan commented on server/controllers/notification.js
> +  console.log(findAllByLoggedUser);
Remove please

2022-02-17 18:48 UTC, moffatethan commented on client/src/components/Notifications/Notifications.tsx
> +      const getData = await fetchAllUnreadNotications();
fetchAllUnreadNoti**fi**cations 

Please correct spelling 🙂

2022-02-17 18:49 UTC, moffatethan commented on client/src/helpers/APICalls/getNotifications.ts
> +export async function fetchAllNotications(): Promise<Notifications> {
fetchAllNoti**fi**cations

2022-02-17 18:49 UTC, moffatethan commented on client/src/helpers/APICalls/getNotifications.ts
> +export async function fetchAllNotications(): Promise<Notifications> {
Please update spelling elsewhere in the code

2022-02-17 18:49 UTC, moffatethan reviewed
Still some spelling changes I need to see then I'll approve

2022-02-22 17:44 UTC, moffatethan approved these changes

2022-02-23 15:45 UTC, merged