Stripe connect
hatchways/team-teak pull request #86
Opened 2022-01-29 14:48 UTC by MUGABA

### What this PR does (required):
- This pr will help a merchant customer to create a stripe account and link

### Any information needed to test this feature (required):
- I User must have an active stripe account

### Any issues with the current functionality (optional):
- Implementation not test fully because I did not have an active stripe account.

2022-01-31 19:09 UTC, ezeilo-su commented
Hey @MUGABA, please link the ticket for this PR.

2022-01-31 20:29 UTC, ezeilo-su requested changes
Hey @MUGABA, good progress here. Please look at the comments I left and address them.

2022-01-31 20:29 UTC, ezeilo-su commented on server/controllers/stripeConnect.js
> +  return res.status(201).send({ success: petSitter });
Please use a `try`/`catch` block

2022-01-31 20:29 UTC, ezeilo-su commented on server/controllers/stripeConnect.js
> +  const profile = await Profile.findOne().where("userId").equals(userId);
Please use a `try`/`catch` block

2022-02-04 15:18 UTC, MUGABA commented on server/controllers/stripeConnect.js
> +  const { id } = account;
Thanks for the pointer I did test it and it works well

2022-02-09 20:27 UTC, moffatethan commented on client/src/pages/Settings/Settings.tsx
> +    component: <StripeConnect />,
This isn't for payment methods, let's just make a new settings page called 'Billing' or 'Stripe'

2022-02-09 20:27 UTC, moffatethan commented on server/controllers/stripeConnect.js
> +    throw new Error("Stripe ccount not created", err);
```suggestion
    throw new Error("Stripe account not created", err);
```

2022-02-09 20:27 UTC, moffatethan commented on server/controllers/stripeConnect.js
> +      return_url: "http://localhost:3000/dashboard",
Let's make these environment variables for easier production launch

2022-02-09 20:27 UTC, moffatethan commented on server/controllers/stripeConnect.js
> +  });
I think we should make a new page for editing the pet sitter fields

2022-02-12 06:12 UTC, merged