worked on socket.io set up for both the backend and frontend
hatchways/team-teak pull request #87
Opened 2022-01-29 20:09 UTC by MUGABA

### What this PR does (required):
- This was just a setup for socket.io

2022-01-31 19:10 UTC, ezeilo-su commented
Hey @MUGABA, please link the ticket for this PR.

2022-02-09 20:32 UTC, moffatethan requested changes

2022-02-09 20:32 UTC, moffatethan commented on server/utils/socket.js
> +    console.log({ token: socket.handshake.token, user: socket.handshake.user }); // bar
Remove the comment please 🙂

2022-02-09 20:32 UTC, moffatethan commented on server/utils/socket.js
> +  });
We should just establish the authenticated connection and do nothing more

2022-02-15 22:09 UTC, moffatethan approved these changes

2022-02-16 06:14 UTC, merged