finished rendering routes according to account type
hatchways/team-teak pull request #89
Opened 2022-01-30 18:23 UTC by MUGABA

### What this PR does (required):
- This pr renders routes according to account type

2022-02-05 17:48 UTC, ezeilo-su reviewed
Good progress on this one.

2022-02-09 20:42 UTC, moffatethan requested changes

2022-02-09 20:42 UTC, moffatethan commented on client/src/pages/routes/route.ts
> +      routes.push(route);
Logically this doesn't make a ton of sense. If the canView is for example `[AccountType.SUPER_ADMIN, AccountType.OWNER]` then `AccountType.ADMIN` would be able to view it. This isn't very secure. We should only be rendering the route based if their account type is included in the routes. `Array.includes` is the method.

2022-02-15 22:10 UTC, moffatethan requested changes

2022-02-15 22:10 UTC, moffatethan commented on client/src/pages/routes/route.ts
> +    canView: [AccountType.PET_OWNER, AccountType.PET_SITTER],
Okay, so if the canView is null it's public and accessible by everyone. We don't want to restrict auth pages to logged in users.

2022-02-17 19:18 UTC, moffatethan approved these changes

2022-02-17 19:20 UTC, merged