worked on creating payment intent for a customer
hatchways/team-teak pull request #96
Opened 2022-02-02 12:25 UTC by MUGABA

### What this PR does (required):
- This pr creates a payment intent for a customer

![Screenshot 2022-02-02 152427](https://user-images.githubusercontent.com/42658956/152153237-ada62c6e-a60a-41cd-8f17-98174158b246.png)

2022-02-02 22:07 UTC, ezeilo-su requested changes
Hey @MUGABA, good work with this one. I have left you a few comments to address.
Happy coding!

2022-02-02 22:07 UTC, ezeilo-su commented on client/src/components/PaymentMethods/paymentMethods.tsx
> +    // <Redirect to={`${result.url}`} />;
Please remove comment

2022-02-02 22:07 UTC, ezeilo-su commented on client/src/components/PaymentMethods/paymentMethods.tsx
> +    console.log(result);
Please watch for unnecessary logs to the console. Going forward, we should be cleaning up our logs done during development. Thanks!

2022-02-02 22:07 UTC, ezeilo-su commented on client/src/components/PaymentMethods/paymentMethods.tsx
> +    console.log('Am called');
Remove this one

2022-02-09 20:52 UTC, moffatethan requested changes

2022-02-09 20:52 UTC, moffatethan commented on server/controllers/paymentMethods.js
> +    throw new Error("Payment Intent not created");
```suggestion
    throw new Error("SetupIntent not created");
```

2022-02-15 22:10 UTC, moffatethan approved these changes

2022-02-16 06:15 UTC, merged